name: Django Tests

on:
  push:
    branches:
      - 'feature/TS-**'
      - 'bug/TS-**'
      - 'fix/TS-**'
      - 'task/TS-**'

  pull_request:
    branches:
      - master
      - development
      - staging

jobs:
  test-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: actions/cache@v2
      id: cache-venv
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - name: Install
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install -r requirements.txt
    - name: Django Testing
      env:
        DATABASES: ${{ development.DATABASES }}
        DEBUG: ${{ development.DEBUG }}
      run: |
        python3 manage.py test
        