name: Django Tests

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  test-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
    - name: Django Testing
      run: |
        python3 manage.py test
        