name: Django Tests

on:
  push:
    branches:
      - 'feature/TS-**'
      - 'bug/TS-**'
      - 'fix/TS-**'
      - 'task/TS-**'

  
  pull_request:
    branches:
      - master
      - development
      - staging
      

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  test-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Django Testing
      env:
        DATABASES: ${{ secrets.DATABASES }}
        DEBUG: ${{ secrets.DEBUG }}
      run: |
        python3 manage.py test
        