name: Django Tests

on:
  push:
    branches:
      - 'feature/TS-**'
      - 'bug/TS-**'
      - 'fix/TS-**'
      - 'task/TS-**'

  
  pull_request:
    branches:
      - master
      - development
      - staging
      

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  test-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
    - uses: actions/cache@v2
      id: cache-venv  # name for referring later
      with:
        path: ./.venv/  # what we cache: the virtualenv
        # The cache key depends on requirements.txt
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - run: python -m venv ./.venv && . ./.venv/bin/activate && 
           pip install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'
    - name: Django Testing
      env:
        DATABASES: ${{ secrets.DATABASES }}
        DEBUG: ${{ secrets.DEBUG }}
      run: |
        python3 manage.py test
        